from .import res_partner
from .import sale
from .import piano_rinnovo
from .import motivazioni
from .import prodotti_da_approvvigionare
from .import purchase
from .import piano_rate
from .import account_move
from .import sale_invoice
from .import product
