{
    "name": "Esercizio",
    "summary": "Esercizio",
    "version": "17.0.1.0.0",
    "depends": ["base","sale","contacts","account","product",
                "l10n_it_edi","sale_management",
                "mail","sales_team", "purchase",],
    "data": [
        "views/group.xml",
        'security/ir.model.access.csv',
        "views/motivazioni.xml",
        "views/res_partner.xml",
        "views/sale_order.xml",
        "views/piano_rinnovo.xml",
        "views/purchase.xml",
        "views/piano_rate.xml",
        "wizard/wizard.xml",
        "views/account_move.xml",
        "views/product.xml",
             ],
    'installable': True,
    'auto_install': True,
    'license': 'LGPL-3',
}
